# Generated by Django 2.1.1 on 2019-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ig', '0003_auto_20190501_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
